# rust formatter rules.
# check configuration fields here: https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

# We need to support `cargo fmt` for crates.io
edition = "2021"
tab_spaces = 4
match_block_trailing_comma = true
max_width = 120
force_explicit_abi = true
newline_style = "Unix"
use_field_init_shorthand = true
